import getPickListValues from "app/admin/picklists/queries/getPickListValues"
import getUsers from "app/admin/users/queries/getUsers"
import { AppConstants } from "shared-ui"

export const storeLocationFormSchema = {
  title: "New Store Location",
  description: "New store",
  type: "object",
  sections: [
    {
      name: "Information",
      fields: [
        {
          name: "id",
          type: "textfield",
          dataType: "string",
          label: "Store ID",
          minLength: 10,
          required: true,
        },
        {
          name: "storename",
          type: "textfield",
          dataType: "string",
          label: "Store Name",
          required: true,
        },
        {
          name: "storeemail",
          type: "textfield",
          dataType: "string",
          label: "Store Email",
          required: false,
        },
        {
          name: "primarypointofcontact",
          type: AppConstants.fieldTypes.searchUnmerged,
          dataType: "string",
          label: "Primary Contact",
          required: false,
          dataSource: getUsers,
          where: {},
          getOptionLabel: (option) => option.name,
          getValueLabel: (option) => option?.id,
        },
        {
          name: "storephone",
          type: "textfield",
          dataType: "number",
          label: "Store Phone#",
          required: false,
        },
        {
          name: "faxnumber",
          type: "textfield",
          dataType: "number",
          label: "Store Fax#",
          required: false,
        },
        {
          name: "region",
          type: AppConstants.fieldTypes.dropdownWithDBSource,
          dataType: "string",
          label: "Region",
          required: false,
          table: "picklist",
          fieldid: "Store_Region",
          getOptionLabel: (option) => option.valueName,
        },
        {
          name: "regioncode",
          type: "textfield",
          dataType: "string",
          label: "Region Code",
          required: false,
        },
        {
          name: "storeopendate",
          type: "date",
          dataType: "date",
          label: "Store Open Date",
          required: false,
        },
      ],
    },
    {
      name: "Address",
      fields: [
        {
          name: "address",
          type: "textfield",
          dataType: "string",
          label: "Address",
          required: true,
        },
        {
          name: "country",
          type: "textfield",
          dataType: "string",
          label: "Country",
          required: true,
        },
        {
          name: "city",
          type: "textfield",
          dataType: "string",
          label: "City",
          required: true,
        },
        {
          name: "stateprovince",
          type: "textfield",
          dataType: "string",
          label: "State/Province",
          required: true,
        },
        {
          name: "postalcode",
          type: "textfield",
          dataType: "number",
          label: "Postal Code",
          required: false,
        },
        {
          type: AppConstants.fieldTypes.divider,
        },
        {
          name: "latitude",
          type: "textfield",
          dataType: "number",
          label: "Latitude",
          required: false,
        },
        {
          name: "longitude",
          type: "textfield",
          dataType: "number",
          label: "Longitude",
          required: false,
        },
      ],
    },
    {
      name: "Store Management Team",
      fields: [
        {
          name: "storemanager",
          type: AppConstants.fieldTypes.searchUnmerged,
          dataType: "string",
          label: "Store Manager",
          required: false,
          dataSource: getUsers,
          where: {},
          getOptionLabel: (option) => option.name,
          getValueLabel: (option) => option?.id,
        },
        {
          type: AppConstants.fieldTypes.divider,
        },
        {
          name: "facilitymanager",
          type: AppConstants.fieldTypes.searchUnmerged,
          dataType: "string",
          label: "Facility Manager",
          required: false,
          dataSource: getUsers,
          where: {},
          getOptionLabel: (option) => option.name,
          getValueLabel: (option) => option?.id,
        },
        {
          name: "leadfacilitymanager",
          type: AppConstants.fieldTypes.searchUnmerged,
          dataType: "string",
          label: "Lead Facility Manager",
          required: false,
          dataSource: getUsers,
          where: {},
          getOptionLabel: (option) => option.name,
          getValueLabel: (option) => option?.id,
        },
      ],
    },
    {
      name: "Additional Information",
      fields: [
        {
          name: "venue",
          type: AppConstants.fieldTypes.dropdownWithDBSource,
          dataType: "string",
          label: "Venue",
          table: "picklist",
          fieldid: "Store_Venue",
          getOptionLabel: (option) => option.valueName,
        },
        {
          name: "subvenue",
          type: AppConstants.fieldTypes.dropdownWithDBSource,
          dataType: "string",
          label: "Sub Venue",
          table: "picklist",
          fieldid: "Store_Sub_Venue",
          getOptionLabel: (option) => option.valueName,
        },
        {
          name: "concept",
          type: "textfield",
          dataType: "string",
          label: "Concept",
          required: false,
        },
        {
          name: "dma",
          type: "textfield",
          dataType: "string",
          label: "DMA",
          required: false,
        },
        {
          name: "company",
          type: "textfield",
          dataType: "string",
          label: "Company",
          required: false,
        },
        {
          type: AppConstants.fieldTypes.divider,
        },
        {
          name: "status",
          type: AppConstants.fieldTypes.dropdownWithDBSource,
          dataType: "string",
          label: "Status",
          table: "picklist",
          fieldid: "Store_Status",
          getOptionLabel: (option) => option.valueName,
        },
        {
          name: "storecloseddate",
          type: "date",
          dataType: "date",
          label: "Store Closed Date",
        },
        {
          type: AppConstants.fieldTypes.divider,
        },
        {
          name: "remodeldate",
          type: "date",
          dataType: "date",
          label: "Remodel Date",
        },
        {
          name: "refreshdate",
          type: "date",
          dataType: "date",
          label: "Refresh Date",
        },
      ],
    },
  ],
}
