
export const createAssetcatalogSchema = {
  title: "New Asset category",
  fields: [
    {
      name: "name",
      type: "textfield",
      dataType: "string",
      label: "Name",
      required: true,
    },
    {
      name: "email",
      type: "textfield",
      dataType: "string",
      label: "Email",
      required: true,
    },
    {
      name: "phone",
      type: "textfield",
      dataType: "number",
      label: "Phone",
      required: false,
    },
    {
      name: "role",
      type: AppConstants.fieldTypes.dropdownWithDBSourceUnMerged,
      dataType: "string",
      key: "name",
      label: "Role",
      required: true,
      dataSource: getRoles,
      where: {},
      setValueKey: "name",
      getOptionLabel: (option) => option.name,
    },
    {
      name: "profile",
      type: AppConstants.fieldTypes.dropdownWithStaticData,
      key: "profile",
      dataType: "string",
      label: "Profile",
      required: true,
      dropdownData: AppConstants.profileValues,
      getOptionLabel: (option) => option,
    },
    {
      name: "manager",
      type: AppConstants.fieldTypes.searchUnmerged,
      dataType: "string",
      label: "Manager",
      required: true,
      dataSource: getUsers,
      where: {},
      getOptionLabel: (option) => option.name,
      getValueLabel: (option) => option?.id,
    },
    {
      name: "status",
      type: AppConstants.fieldTypes.dropdownWithDBSource,
      key: "status",
      dataType: "string",
      label: "Status",
      required: true,
      table: "picklist",
      fieldid: "User_Status",
      getOptionLabel: (option) => option.valueName,
    },
  ],
}
