INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (1, 100, 1000, 1, 'Backflow Device', 'Plumbing', 'Normal', 500, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (2, 100, 1000, 2, 'Drink Station', 'Handyman', 'Normal', 500, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (3, 100, 1000, 3, 'Fryer', 'Cooking Equipment', 'Normal', 500, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (4, 100, 1000, 4, 'Grill', 'Cooking Equipment', 'Normal', 500, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (5, 100, 1000, 5, 'Ice Machine', 'Ice Machine', 'Emergency', 550, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (6, 100, 1000, 6, 'Rice Cooker', 'Cooking Equipment', 'Normal', 500, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (7, 100, 1000, 7, 'RTU', 'RTU', 'Emergency', 600, true, false, NOW(), NOW(), -2, -2);
INSERT INTO public."AssetCatalog"(id, tenantid, storeid, equipment_reference_id, name, primarytrade, default_wo_priority, avg_repair_nte, is_active, isdeleted, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (8, 100, 1000, 8, 'Walk-in Cooler', 'Refrigeration', 'Emergency', 600, true, false, NOW(), NOW(), -2, -2);

INSERT INTO public."AssetInfo"(id, tenantid, storeid, assetcatalogid, zone, name, model_num, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (DEFAULT, 100, 1000, 1, 'Exterior', 'Main Backflow Device', 'WILKINBFD1234', NOW(), NOW(), -2, -2);
INSERT INTO public."AssetInfo"(id, tenantid, storeid, assetcatalogid, zone, name, model_num, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (DEFAULT, 100, 1000, 1, 'Exterior', 'Irrigation Backflow Device', 'WILKINBFD2345', NOW(), NOW(), -2, -2);

INSERT INTO public."AssetInfo"(id, tenantid, storeid, assetcatalogid, zone, name, model_num, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (DEFAULT, 100, 1000, 2, 'Dining Room', 'DR Drink Machine', 'DR12345', NOW(), NOW(), -2, -2);
INSERT INTO public."AssetInfo"(id, tenantid, storeid, assetcatalogid, zone, name, model_num, "createdAt", "updatedAt", "createdBy", "updatedBy") VALUES (DEFAULT, 100, 1000, 2, 'Drive-Thru', 'DT Drink Machine', 'DR2345', NOW(), NOW(), -2, -2);